### ISSUE TITLE
'No input classes found' for gradle > 3.5.1

### ISSUE THREAD

**Issue by Zasch** [vojtechhabarta/typescript-generator#163]
Hi,

it seems the gradle plugin stopped working with the newest gradle versions. I used 4.0.2 and got the following output:

```
:generateTypeScript
Running TypeScriptGenerator version 1.27.339
Scanning classpath
Scanning finished in 1,33 seconds. Total number of classes: 22282.
Found 0 classes matching pattern.
No input classes found.
:generateTypeScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTypeScript'.
> No input classes found.
```

I found, that using gradle 3.5.1 everything works as expected.
So my guess would be, that the mechanism to determine the class files on the classpath changed a bit in gradle.

**Comment by vojtechhabarta** [comment]
Do you think it is just classpath scanning broken or even class loading?
I mean if you could specify some class using `classes` parameter and test if it works.

**Comment by Zasch** [comment]
Looks like class loading is broken, too. This time I also got a ClassNotFoundException:
```
:generateTypeScript
Running TypeScriptGenerator version 1.27.339
Error: Cannot load class 'my.model.Clazz'
java.lang.ClassNotFoundException: my.model.Clazz
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at cz.habarta.typescript.generator.Input.loadClasses(Input.java:120)
        at cz.habarta.typescript.generator.Input.fromClassNames(Input.java:106)
        at cz.habarta.typescript.generator.Input.fromClassNamesAndJaxrsApplication(Input.java:42)
        at cz.habarta.typescript.generator.gradle.GenerateTask.generate(GenerateTask.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
No input classes found.
:generateTypeScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTypeScript'.
> No input classes found.
```

**Comment by vojtechhabarta** [comment]
I installed Gradle 4.0.2 and tried it on https://github.com/vojtechhabarta/typescript-generator/tree/master/sample-gradle but it worked normally. I also tried some class glob pattern and I also added some dependency and tried to use classes from it. Everything worked.

Do you still have this problem? It must be something special. Can you try it with latest typescript-generator and latest 4.x Gradle?

**Comment by Zasch** [comment]
This time I got another error message:
`
:compileJava NO-SOURCE
:generateTypeScript
Running TypeScriptGenerator version 1.29.355
Scanning classpath
Scanning finished in 0,73 seconds. Total number of classes: 34339.
Found 0 classes matching pattern.
No input classes found.
:generateTypeScript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateTypeScript'.
> No input classes found.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateTypeScript'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: No input classes found.
        at cz.habarta.typescript.generator.Input.fromClassNamesAndJaxrsApplication(Input.java:56)
        at cz.habarta.typescript.generator.gradle.GenerateTask.generate(GenerateTask.java:153)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more


BUILD FAILED in 2s
1 actionable task: 1 executed
`

My build.gradle looks like this:

`
buildscript {
    ext {
        springBootVersion = '1.5.2.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath "io.spring.gradle:dependency-management-plugin:0.5.6.RELEASE"
        classpath('cz.habarta.typescript-generator:typescript-generator-gradle-plugin:1.+')
    }
}

apply plugin: 'groovy'
apply plugin: 'org.springframework.boot'
apply plugin: 'cz.habarta.typescript-generator'
apply plugin: 'io.spring.dependency-management'

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile('org.springframework.boot:spring-boot-starter')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.codehaus.groovy:groovy')
    compile('com.fasterxml.jackson.datatype:jackson-datatype-jsr310')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}

generateTypeScript {
    jsonLibrary = 'jackson2'
    classPatterns = ['my.app.model.*']
    outputFile = 'build/myapp.d.ts'
    outputKind = 'global'
    namespace = 'myapp'
}
`

**Comment by vojtechhabarta** [comment]
@Zasch I just merged #198 from @jechlin, maybe it solves your problem too.

**Comment by Zasch** [comment]
Thanks, I will have a look next week.

**Comment by jechlin** [comment]
It should fix it.  @vojtechhabarta it would have  worked previously with https://github.com/vojtechhabarta/typescript-generator/tree/master/sample-gradle because the types are in java, not groovy.  

This is what causes the problem - https://docs.gradle.org/4.0/release-notes.html#multiple-class-directories-for-a-single-source-set - the workaround there would also work undoubtedly.

Thanks, jamie

**Comment by Zasch** [comment]
Unfortunately it didn't fix it.
But I'm pretty sure it works on another project with an almost identical setup.
I need to dig a little deeper when I find the time...

**Comment by jeanettehead** [comment]
I'm experiencing this too. I have a kotlin project that works great with gradle 3.5.1 but doesn't work at all with newer versions.

**Comment by vojtechhabarta** [comment]
@jeanettehead have you tried typescript-generator version 1.30.381 or later? It has some fix for Gradle. If not could you please try latest version (1.30.383)?

**Comment by jechlin** [comment]
Sorry to butt in here. I think the fix @vojtechhabarta is talking about is not going to help, because it only adds the groovy output directory to the classpath. Problem is that won't work for kotlin, scala, and whatever other JVM-language is supported by gradle. IMHO we should either add the most common languages, ie java, groovy, kotlin, scala, or better, programatically find all the output dirs (I don't know how to do that but I could take a look). Or final possibility is allow specifying it as a config option.

**Comment by vojtechhabarta** [comment]
Aha, @jechlin you are right, I just check your PR #198 and it is really for groovy only.

Ideal solution would be to have some mechanism which works without configuration for all languages. Maybe it could be possible to somehow recognize all "compile" tasks like `compileJava`, `compileGroovy`, etc. and use them or maybe we could use all tasks but I don't know if this could add unwanted files.

If we didn't have any solution which would work without configuration we could add configuration parameter which would specify list of "compile" tasks (something like `classpathFromTasks`) which would by default have value with list of common languages like java, groovy, kotlin, scala.

In any case help is appreciated.

**Comment by jechlin** [comment]
I was just working on a PR last night which will detect the "compile" tasks. When I say "detect", what I mean is simply if the task name starts with "compile", but all of the language compilation tasks seem to follow that pattern.

I'm not officially working today but should be able to send the PR over by end of day.
cheers, jamie

**Comment by jechlin** [comment]
@jeanettehead - please could you test the version from the PR. You can make simple changes to your build file to test it without @vojtechhabarta having to build/tag/release etc. Instructions are in the PR: https://github.com/vojtechhabarta/typescript-generator/pull/205.
thanks

**Comment by jeanettehead** [comment]
@jechlin that works for me! I did the following things to test it:

1. re-verified that my existing code didn't work with gradle 4.4.1
1. followed the instructions in the README on your PR to change the dependency
1. generated typescript successfully with that change
1. added a new data class to be generated into typescript
1. ran it again and verified that the new class was generated

Thanks for doing the PR 👍

**Comment by jechlin** [comment]
Awesome, thanks for letting us know.

**Comment by vojtechhabarta** [comment]
Released [v1.30.385](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.30.385) with #205.

**Comment by vojtechhabarta** [comment]
Groovy, Kotlin and Scala is fixed, closing the issue.
